#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     bottomLimitSwitch, sensorTouch)
#pragma config(Sensor, S4,     rangeFinder,     sensorSONAR)
#pragma config(Motor,  motorA,          IrScanner,     tmotorNXT, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     left,          tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     right,         tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     lift,          tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     nada,          tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    TubeGrab,             tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    ScoopGate,            tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

#include "DriveSingleEncoder.c"
//#include "MoveSingleTiming.c"


task main()
{
	while(true)
	{
	    char    buffer[16];
	    sprintf(buffer,"%d",nMotorEncoder[lift]);
	    nxtDisplayBigTextLine(4, buffer);

	    if(nNxtButtonPressed == 1) // if the current pressed button is 1 (the Right Arrow):
			 {
		 	  motor[lift] = 100;  // Lift the scoop
		 	 }
	    else if(SensorValue(bottomLimitSwitch) == 1)
		     {
			  motor[lift] = 0;
			  nMotorEncoder[lift] = 0;
			 }
		else if(nNxtButtonPressed == 2) // if the current pressed button is 2 (the Left Arrow):
			 {
		 	  motor[lift] = -100; // Drop the scoop
		 	 }
	 	else
	    {
	     motor[lift] = 0;
	    }
	}
}
