#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     bottomLimitSwitch, sensorTouch)
#pragma config(Sensor, S4,     rangeFinder,     sensorSONAR)
#pragma config(Motor,  motorA,          IrScanner,     tmotorNXT, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     left,          tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     right,         tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     lift,          tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     nada,          tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    TubeGrab,             tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    ScoopGate,            tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

#include "DriveSingleEncoder.c"
//#include "MoveSingleTiming.c"


void Position1route()
{
    straight(70, 25);
    wait1Msec(200);
    pivot(100,90);
    wait1Msec(200);
    straight(70,-29);
    wait1Msec(500);
    spin(70,-90);
    wait1Msec(200);
    liftHeight(100,23.622);
    wait1Msec(200);
    straight(70,52);
    wait1Msec(200);
    straight(50,4);
    //drop ball in 60
    openScoopGate(true);
    wait1Msec(1000);
    straight(70,-6);
    wait1Msec(200);
    spin(70,-180);
    wait1Msec(200);
    straight(35,-6);
    wait1Msec(200);
}

task main()
{
    static const short NoButton         = -1;
    static const short ExitButton       =  0;
    static const short RightButton      =  1;
    static const short LeftButton       =  2;
    static const short EnterButton      =  3;
    static const short InitialUninited  =  0;

    int action = InitialUninited;
    bool actionSelector = true; // wil this work  or will it point to what ever is in the 1 place in ram.
    bool grabBase = true;
    char *actionString = "grab";
        float shiftover = 60;
            float jiggle = 30;

    while (actionSelector)
    {
        nxtDisplayBigTextLine(4, actionString); //To print choosen style of base autonomous.

        switch(nNxtButtonPressed)
        {
        case ExitButton:
        case RightButton:
            grabBase = true;
            actionString = "grab"; //Click the right arrow on nxt to select grabber sequence. Will print "grab" on NXT screen.
            break;
        case LeftButton:
            grabBase = false;
            actionString = "no grab"; // Click the left arrow button on nxt to select no grabber sequence. Will print "no grab" on NXT screen.
            break;
        case EnterButton:
            actionSelector = false;
            break;
        }
    }

    /*
    Waiting for the start signal to the samatha after program has been selected.
    Pressing the back button will still exit  this programming if deemed unnecessary.
    */
    waitForStart();

    resetLift();
    grabTubeBase(false);
    openScoopGate(false);
    liftHeight(100,6);
    straight(70,12);
    wait1Msec(200);
    if (SensorValue[rangeFinder] < 255)
    {
        //if less than 255 it should be about 110 which means position 1
        Position1route();
    }
    else
    {
        pivot(70, shiftover);
        wait1Msec(200);
        spin(70, -shiftover);
        wait1Msec(200);
        if (SensorValue[rangeFinder] < 255)
        {
            //if less than 255 the tower is in position 3
            pivot(70, -shiftover);
            wait1Msec(200);
            spin(70, shiftover);
            wait1Msec(200);
            straight(70,24);
            wait1Msec(200);
            pivot(70,-45);
            wait1Msec(200);
        }
        else
        {
            //position 2
            pivot(70, -jiggle);
            wait1Msec(200);
            spin(70, jiggle);
            wait1Msec(200);
            straight(70, 18);
            wait1Msec(200);
            pivot(70, -60);
            wait1Msec(200);
        }
    }

    if(grabBase)
    {
        grabTubeBase(true);
        liftHeight(100,6);
        wait1Msec(200);
        //use grabber to get the rolling goal
        straight(70,64);
        wait1Msec(200);
        spin(70,-45);
        wait1Msec(200);
        straight(70,38);
        wait1Msec(200);
        spin(70,-135);
        wait1Msec(200);
        grabTubeBase(false);
    }
    resetLift();
    while(true);
}
