#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     left,          tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     right,         tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void test()
	{
		motor[left] = 100;
		motor[right] = 100;
		wait1Msec(1000);

		motor[left] = 50;
		motor[right] = 50;
		wait1Msec(1000);

		motor[left] = 25;
		motor[right] = 25;
		wait1Msec(1000);

	}
task main()
{
	test();
}
