#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     bottomLimitSwitch, sensorTouch)
#pragma config(Sensor, S3,     topLimitSwitch, sensorTouch)
#pragma config(Sensor, S4,     IrSeeker,       sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  motorA,          IrScanner,     tmotorNXT, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     left,          tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     right,         tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     lift,          tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     nada,          tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    TubeGrab,             tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c";
//#include "MoveSingleTiming.c";
#include "DriveSingleencoder.c";

// buttons should be an enum, but compiler wasn't handling properly...
static const short X_Btn = 1;
static const short A_Btn = 2;
static const short Y_Btn = 4;
static const short B_Btn = 3;
static const short TopLeft_Btn = 5;
static const short TopRight_Btn = 6;
static const short LowLeft_Btn = 7;
static const short LowRight_Btn = 8;
static const short Back_Btn = 9;
static const short Start_Btn = 10;
static const short LJoyPress_Btn = 11;
static const short RJoyPress_Btn = 12;


#define DRIVE_STOP_BTN  joy1Btn(A_Btn)
#define DRIVE_BOOST_BTN joy1Btn(LowRight_Btn)
#define DRIVE_FINE_BTN  joy1Btn(TopRight_Btn)
#define joyLeft joystick.joy1_y1
#define joyRight joystick.joy1_y2
#define LIFT_RAISE joy2Btn(TopLeft_Btn)
#define LIFT_LOWER joy2Btn(LowLeft_Btn)
#define BASE_RELEASE joy2Btn(LowRight_Btn)
#define BASE_GRAB joy2Btn(TopRight_Btn)
#define ARRAY_LENGTH(x) ((sizeof(x))/(sizeof(x[0])))
#define AUTO_LIFT_SPEED 100
#define TWEAK_LIFT_SPEED 60

task main()
{
    waitForStart();
    straight(70, 80);
    wait1Msec(200);
    straight(70, -6);
    wait1Msec(200);
    spin(70,180);
    wait1Msec(200);
    straight(70,-14);
    wait1Msec(200);
    pivot(70,-45);
    wait1Msec(200);
    straight(70,33);
    wait1Msec(200);
    pivot(70,45);
    wait1Msec(200);
    straight(70,42);
    wait1Msec(200);
    spin(70,90);

}// end task main
