#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     bottomLimitSwitch, sensorTouch)
#pragma config(Sensor, S3,     topLimitSwitch, sensorTouch)
#pragma config(Sensor, S4,     IrSeeker,       sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  motorA,          IrScanner,     tmotorNXT, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     left,          tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     right,         tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     lift,          tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     nada,          tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    TubeGrab,             tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    ScoopGate,            tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c";
#include "MoveSingleTiming.c";

// buttons should be an enum, but compiler wasn't handling properly...
static const short X_Btn = 1;
static const short A_Btn = 2;
static const short Y_Btn = 4;
static const short B_Btn = 3;
static const short TopLeft_Btn = 5;
static const short TopRight_Btn = 6;
static const short LowLeft_Btn = 7;
static const short LowRight_Btn = 8;
static const short Back_Btn = 9;
static const short Start_Btn = 10;
static const short LJoyPress_Btn = 11;
static const short RJoyPress_Btn = 12;


#define DRIVE_STOP_BTN  joy1Btn(A_Btn)
#define DRIVE_BOOST_BTN joy1Btn(LowRight_Btn)
#define DRIVE_FINE_BTN  joy1Btn(TopRight_Btn)
#define joyLeft joystick.joy1_y1
#define joyRight joystick.joy1_y2

#define LIFT_RAISE joy2Btn(TopLeft_Btn)
#define LIFT_LOWER joy2Btn(LowLeft_Btn)
#define AUTO_LIFT_SPEED 100
#define TWEAK_LIFT_SPEED 60
#define BASE_RELEASE joy2Btn(LowRight_Btn)
#define BASE_GRAB joy2Btn(TopRight_Btn)
#define GATE_OPEN joy2Btn(B_Btn)
#define GATE_CLOSE joy2Btn(A_Btn)

#define ARRAY_LENGTH(x) ((sizeof(x))/(sizeof(x[0])))


float joystickMotorMapping(short controlInput, float maxOutput_pct, short deadzone)
{
    float output;

    if (controlInput <= -128 + deadzone)
    {
        output = -maxOutput_pct;
    }
    else if (( controlInput >= -deadzone)
        && ( controlInput <= deadzone))
    {
        output = 0;
    }
    else if (controlInput >= 127 - deadzone)
    {
        output = maxOutput_pct;
    }
    else if (controlInput < -deadzone)
    {
        output = (-maxOutput_pct / (-128 + 2*deadzone)) * (controlInput + deadzone);
    }
    else
    {
        output = (-maxOutput_pct / (-127 + 2*deadzone)) * (controlInput + deadzone);
    }

    return output;
}

task main()
{
    int lastCmdTweak = 1;
    motor[lift] = 0;
    nMotorEncoder[lift] = 0;
    long encoderTargets[] = {0,11500,22650,33650};
    int targetIndex = 0;
    int length = ARRAY_LENGTH(encoderTargets);
    char    buffer[16];
      int isLastLiftRaise = 0;
    int isLastLiftLower = 0;
    int fineRange = 360;
    int liftDeadZone = 100;

    waitForStart();

    while(true)
    {
        int deadzone = 5;

        getJoystickSettings(joystick);

        float FullSpeed_pct = 70;

        if ((DRIVE_STOP_BTN)
           ||bDisconnected)
        {
            driveStop();
        }
        else
        {
            if (DRIVE_BOOST_BTN)
            {
                FullSpeed_pct = 100;
            }
            else if (DRIVE_FINE_BTN)
            {
                FullSpeed_pct = 40;
            }
            drive(joystickMotorMapping(joyLeft, FullSpeed_pct, deadzone),
                  joystickMotorMapping(joyRight, FullSpeed_pct, deadzone));
         }

         if (joystick.joy2_TopHat == 0)
        {
            lastCmdTweak = 1;
            motor[lift] = TWEAK_LIFT_SPEED;
            nxtDisplayBigTextLine(5 , "up" );
        }
        else if ((joystick.joy2_TopHat == 4)
          &&  (SensorValue[bottomLimitSwitch] == 0))
        {
            lastCmdTweak = 1;
            motor[lift] = -TWEAK_LIFT_SPEED;
            nxtDisplayBigTextLine(5 , "down" );
        }
        else if(LIFT_RAISE)
        {
            if(((targetIndex+1) < length) &&
               (isLastLiftRaise == 0))
            {
                lastCmdTweak = 0;
                targetIndex++;
                motor[lift] = AUTO_LIFT_SPEED;
                nxtDisplayBigTextLine(5 , "i-up" );
                isLastLiftRaise = 1;
             }
       }
       else if (SensorValue[bottomLimitSwitch] != 0)
       {
           nMotorEncoder[lift] = 0;
           motor[lift] = 0;
       }
       else if(LIFT_LOWER)
       {
            if((targetIndex > 0) && (isLastLiftLower == 0))
            {
                lastCmdTweak = 0;
                targetIndex--;
                motor[lift] = -AUTO_LIFT_SPEED;
                nxtDisplayBigTextLine(5 , "i-down" );
                isLastLiftLower = 1;
            }
       }
       else if (lastCmdTweak)
       {
               motor[lift] = 0;
       }

       if (!lastCmdTweak)
       {
           if (encoderTargets[targetIndex] > nMotorEncoder[lift] + fineRange)
                motor[lift] = AUTO_LIFT_SPEED;
           else if (encoderTargets[targetIndex] > nMotorEncoder[lift] + liftDeadZone)
               motor[lift] = AUTO_LIFT_SPEED / 2;
           else if (encoderTargets[targetIndex] < nMotorEncoder[lift] - fineRange)
               motor[lift] = -AUTO_LIFT_SPEED;
           else if (encoderTargets[targetIndex] < nMotorEncoder[lift] - liftDeadZone)
               motor[lift] = -AUTO_LIFT_SPEED / 2;

           else
           {
               motor[lift] = 0;
           }
       }

      if(!LIFT_RAISE)
      {
            isLastLiftRaise = 0;
      }
      if(!LIFT_LOWER)
      {
            isLastLiftLower = 0;
      }
        sprintf(buffer, "%d", nMotorEncoder[lift]);
        nxtDisplayBigTextLine(1 , buffer );
        sprintf(buffer, "%d", encoderTargets[targetIndex]);
        nxtDisplayBigTextLine(3 , buffer );
        if (BASE_GRAB)
        {
            servo[TubeGrab]= ServoValue[TubeGrab] + 2;
        }
           if (BASE_RELEASE)
        {
            servo[TubeGrab]= ServoValue[TubeGrab] - 2;
        }
        if (GATE_OPEN)
        {
            servo[ScoopGate]= ServoValue[ScoopGate] + 4;
        }
           if (GATE_CLOSE)
        {
            servo[ScoopGate]= ServoValue[ScoopGate] - 4;
        }
        } // Infinite while
}// end task main
