#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     left,          tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     right,         tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
getJoystickSettings(joystick);
#define joyLeft joystick.joy1_y1;
#define joyRight joystick.joy1_y2;
void drive()
{
	if(-5>joyLeft>5 && -5>joyRight>5)
	{
	motor[left]=joyLeft;
	motor[right]=joyRight;
	}

}
task main()
{
	getJoystickSettings(joystick);
	drive();
}
